---
title: "Effect of tone category on F0 on vowel (collapsed across frames, syllable types), assuming a 4 tone analysis"
output: html_document
---

## 1. Load Data
```{r}
#rm(list=ls())
library(dplyr)
library(Rmisc)
library(ggplot2)

# Load functions
source("functions/YolmoToneProd_Functions.R")

load("output/YolmoTone-allspeakers.RData")
```

## 2. Subset data by position in word
```{r}
YolTone.all0 <- subset(YolTone.df, Position == 0)  # Only select monosyllabic words
YolTone.all1 <- subset(YolTone.df, Position == 1)  # Only select 1st syllables of disyllabic words
YolTone.all2 <- subset(YolTone.df, Position == 2)  # Only select 2nd syllables disyllabic wordss
```

# 2.1 Plot effects of tone category on F0 at rime midpoint
```{r}
# Create summaries of mean F0 for each tone category * gender combination at rime midpoint
summarize_f0_50(YolTone.all0, toneanalysis = "Tone4")
summarize_f0_50(YolTone.all1, toneanalysis = "Tone4")
summarize_f0_50(YolTone.all2, toneanalysis = "Tone4")

# Plot differences in F0 across tone categories conditions
plot_boxplot_f0_rime50(YolTone.all0, toneanalysis = "Tone4", sylltype = "monosyllabic words (all frames)")
plot_boxplot_f0_rime50(YolTone.all1, toneanalysis = "Tone4", sylltype = "1st syllable of disyllabic words (all frames)")
plot_boxplot_f0_rime50(YolTone.all2,  toneanalysis = "Tone4", sylltype = "2nd syllable of disyllabic words (all frames)")

#Save as plots as PNG files
save_boxplot_f0_rime50_png(YolTone.all0, toneanalysis = "Tone4", sylltype = "monosyllabic words (all frames)", filename = "YolTone_4tone_all_f0_rime50_mono")
save_boxplot_f0_rime50_png(YolTone.all1, toneanalysis = "Tone4", sylltype = "1st syllable of disyllabic words (all frames)", filename = "YolTone_4tone_all_f0_rime50_di_1st")
save_boxplot_f0_rime50_png(YolTone.all2, toneanalysis = "Tone4", sylltype = "2nd syllable of disyllabic words (all frames)", filename = "YolTone_4tone_all_f0_rime50_di_2nd")
```

# 2.2 Linear regressions to model F0 at rime midpoint
```{r}
YolTone.all0.lm <- lm(F0 ~ Tone4 + Gender, data = subset_f0_rime50(YolTone.all0))
summary(YolTone.all0.lm)
YolTone.all1.lm <- lm(F0 ~ Tone4 + Gender, data = subset_f0_rime50(YolTone.all1))
summary(YolTone.all1.lm)
YolTone.all2.lm <- lm(F0 ~ Tone4 + Gender, data = subset_f0_rime50(YolTone.all2))
summary(YolTone.all2.lm)
```


## 2.3 Plot F0 across vowel by tone category (normalized duration)
```{r}
# Create summaries of mean F0 for each tone category * gender combination at 1% time intervals
head(summarize_f0_across_time(YolTone.all0, toneanalysis = "Tone4"), 10)
head(summarize_f0_across_time(YolTone.all1, toneanalysis = "Tone4"), 10)
head(summarize_f0_across_time(YolTone.all2, toneanalysis = "Tone4"), 10)


# Plot F0 across rime for each tone category
pd <- position_dodge(5)
YolTone.f0.traj1 <- ggplot(YolTone.f0.summ, aes(x = Time, y = F0, colour = Factor, group = Factor)) + #Use x=Time for equal time
  geom_line(aes(linetype = Factor), size=1.25, position=pd) + #Line type depends on Tone.
  geom_point(data=subset(YolTone.f0.summ, (Time==1|Time==20|Time==40|Time==60|Time==80|Time==100)), aes(shape = Factor), size = 5, position = pd) + #Only show the points for a subset of the data
  geom_errorbar(data = subset(YolTone.f0.summ, (Time==1|Time==20|Time==40|Time==60|Time==80|Time==100)), aes(ymin = F0-sd/2, ymax = F0+sd/2), width = 1.0, position = pd) + #Only show half the NS for a subset of the data
  scale_x_continuous(limits = c(-1,105),
                     breaks = c(0,20,40,60,80,100)) + # Set x range + ticks
  scale_y_continuous(limits = c(100, 240), 
                    breaks = c(100,125,150,175,200,225)) + #Set y range + ticks
  labs(x = "Time (%)", y = "F0 (Hz)", title = expression(paste(italic("f0"), "across time-normalized rime (monosyllable, all frames)"))) +
  theme_bw() +
    theme(axis.title = element_text(size = 16),
        axis.text = element_text(size = 15)) + #Adjust font size of axes
  theme(legend.title = element_text(size = 12),
        legend.text = element_text(size = 11)) + #Adjust size of legend
  theme(plot.title = element_text(size = 16)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_discrete(name = "Gender *\nTone Category", l=50) + # Use darker colors, lightness=50 
  scale_linetype_discrete(name = "Gender *\nTone Category") +
  scale_shape_discrete(name = "Gender *\nTone Category")

YolTone.f0.traj1  # Preview plot

#Save as PNG file
png(file = "figures/YolTone_4tone_f0traj_monosyll.png", width = 600, height = 450, res = 72)
YolTone.f0.traj1
dev.off()
```


## Save RData
```{r}
save.image(file="output/YolmoTone-allspeakers-plots.RData")
```
